# This TravisCI script is very minimal and not very flexible.
# It only tests one environment on Linux with Python 3.7.
# We will eventually want to expand our test environments.
sudo: false
language: python
python:
    - "3.7"
    - "3.8"
env:
    - NUMPY_VERSION="1.19"
    - NUMPY_VERSION="1.18"
    - NUMPY_VERSION="1.17"
    - NUMPY_VERSION="1.16"
    - NUMPY_VERSION="1.15"
    - NUMPY_VERSION="1.14"
    - NUMPY_VERSION="1.13"
    - NUMPY_VERSION="1.12"
    - NUMPY_VERSION="1.11"
    - NUMPY_VERSION="1.10"
    - NUMPY_VERSION="1.9"
    - NUMPY_VERSION="1.8"

install:
    # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda env create -f continuous_integration/environment-${TRAVIS_PYTHON_VERSION}.yml
    - conda activate mg
    - conda install numpy=$NUMPY_VERSION
    - pip install -e .

script:
    - pytest
    - black --check --diff metagraph

after_success:
    - conda install -c conda-forge coveralls
    - coveralls

notifications:
    email: false
