name: mg
dependencies:
# dev environment
  - python=3.7
  - coverage
  - pytest
  - pytest-cov

# metagraph dependencies (so setup.py develop doesn't pip install them)
  - importlib_metadata
  - numpy
  - networkx
  - pandas
  - conda-forge::python-louvain
  - scipy
  - conda-forge::donfig
  - conda-forge::grblas
  - dask
